### ISSUE TITLE
Throttling when sending messages

### ISSUE THREAD

**Issue by asterite** [instedd/mobile-gateway#2]
If the network rejects a message due to a large volume being sent, retry with a (hardcoded) exponential backoff

**Comment by spalladino** [comment]
Add a setting to the LGW on how much time should the gateway wait between sending each message, 10 seconds by default, configurable to be between 10 and 60 seconds.

This policy, together with the new failed messages policy (see #3), should improve the handling of errors, whether due to throttling or to other issues.

**Comment by spalladino** [comment]
New settings screen

![screen shot 2016-04-15 at 4 05 27 pm](https://cloud.githubusercontent.com/assets/429604/14572214/e4282ee8-0323-11e6-8985-efaec18b5cfb.png)

**Comment by pmallol** [comment]
Working ok in version 2.2
